Use byte strings when writing data.
Without this fix, on Python 3, we get errors such as:

  File "/Users/crodrigues/b1/worker/buildbot_worker/commands/transfer.py", line 369, in _writeData
    self.fp.write(data)
builtins.TypeError: a bytes-like object is required, not 'str'