www/ui: Install @types/node
This fixes the following ignored error while building:

src/components/FixedSizeList/FixedSizeList.tsx:165:5 - error TS2580:
Cannot find name 'process'. Do you need to install type definitions for
node? Try `npm i --save-dev @types/node`.

165 if (process.env.NODE_ENV !== 'production') {
        ~~~~~~~