plugins: importlib.metadata use new entry_points interface
dict interface is dropped since Python 3.12

File
"d:\a\buildbot\buildbot\master\buildbot\test\integration\interop\test_commandmixin.py",
line 49, in test_commandmixin
    yield self.setup_config()
File
"C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\twisted\internet\defer.py",
line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
File
"d:\a\buildbot\buildbot\master\buildbot\test\integration\interop\test_commandmixin.py",
line 37, in setup_config
    schedulers.AnyBranchScheduler(name="sched", builderNames=["testy"])
File "d:\a\buildbot\buildbot\master\buildbot\plugins\db.py", line 291,
in __getattr__
    raise AttributeError(str(e)) from e
builtins.AttributeError: Unknown component name: AnyBranchScheduler