util: Break module reference cycle
This fixes the following error which sometimes occurs when running
tests:

Traceback (most recent call last):
  ...
  File ".../master/buildbot/data/test_result_sets.py", line 22
    from buildbot.data import base
  File ".../master/buildbot/data/base.py", line 27
    from buildbot.data import exceptions
  File ".../master/buildbot/data/exceptions.py", line 18
    from buildbot.db.schedulers import SchedulerAlreadyClaimedError
  File ".../master/buildbot/db/schedulers.py", line 25
    from buildbot.db import base
  File ".../master/buildbot/db/base.py", line 24
    from buildbot.util import service
  File ".../master/buildbot/util/service.py", line 29
    import buildbot.config
  File ".../master/buildbot/config/__init__.py", line 17
    from .builder import BuilderConfig  # noqa: F401
  File ".../master/buildbot/config/builder.py", line 21
    from buildbot.db.model import Model
  File ".../master/buildbot/db/model.py", line 55
    class Model(base.DBConnectorComponent):
builtins.AttributeError: partially initialized module
'buildbot.db.base' has no attribute 'DBConnectorComponent'
(most likely due to a circular import)