some more fixes
fix the last resort version number to be 999.0
fix issue in codeparameter build (wrong dest dir for ace)
require distribute > 0.6.30 previous version have a problem:

 error: cannot copy tree 'buildbot_codeparameter/static': not a directory

Signed-off-by: Pierre Tardy <pierre.tardy@intel.com>