makefile: Prevent calling towncrier twice, if it is called from docs-release and docs-release-spelling one after the other.
towncrier 22.8.0.rc1 (2022-08-28) reports duplicate release notes.
See release notes:
  "The detection of duplicate release notes was fixed and recording changes of same version is no longer triggered"
  https://towncrier.readthedocs.io/en/stable/release-notes.html#id81

Traceback from migration from towncrier 21.9.0 to 23.11.0
Traceback (most recent call last):
  File "/tmp/bbvenv/bin//towncrier", line 8, in <module>
    sys.exit(cli())
  File "/tmp/bbvenv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/bbvenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/bbvenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/bbvenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/bbvenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/bbvenv/lib/python3.9/site-packages/towncrier/build.py", line 123, in _main
    return __main(
  File "/tmp/bbvenv/lib/python3.9/site-packages/towncrier/build.py", line 278, in __main
    append_to_newsfile(
  File "/tmp/bbvenv/lib/python3.9/site-packages/towncrier/_writer.py", line 38, in append_to_newsfile
    raise ValueError("It seems you've already produced newsfiles for this version?")
ValueError: It seems you've already produced newsfiles for this version?
make: *** [Makefile:30: docs-towncrier] Error 1