Rename DeprecatedWorkerNameError to DeprecatedWorkerNameWarning
Otherwise warnings looks like some unhandled errors:

    DeprecatedWorkerNameError: 'slavename' attribute is deprecated...