waterfall test: fix instability on latest version of chromedriver
upgrading the chrome-driver, it looks like those tests have an instability

  - Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
      at /buildbot/test/buildbot/smokes/node_modules/protractor/built/browser.js:463:23
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at noRunningBuilds (/buildbot/test/buildbot/smokes/e2e/pages/home.ts:49:24)Error:
      at ElementArrayFinder.applyAction_ (/buildbot/test/buildbot/smokes/node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.<computed> [as getText] (/buildbot/test/buildbot/smokes/node_modules/protractor/built/element.js:91:29)
      at noRunningBuilds (/buildbot/test/buildbot/smokes/e2e/pages/home.ts:49:56)
      at /buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/webdriver.js:938:14
      at /buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/promise.js:2232:22
      at new Promise (<anonymous>)
      at SimpleScheduler.promise (/buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/promise.js:2242:12)
      at SimpleScheduler.execute (/buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/promise.js:2227:17)
      at pollCondition (/buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at /buildbot/test/buildbot/smokes/node_modules/selenium-webdriver/lib/promise.js:2191:7