Try to reclobber on retry.
On a failed git update in clobber mode, I was getting the following
error on the second try:

exceptions.OSError: [Errno 17] File exists: '/path/to/build'

It seems that the clobber only occurs once, and any error that happens
during the checkout should redo the clobber.