steps/trigger: Avoid traceback for UnboundLocalError
Avoid:

File "buildbot/steps/trigger.py", line 200, in worstStatus
    if set(unimportant_brids).issuperset(set(brids_dict.values())):
builtins.UnboundLocalError: local variable 'brids_dict' referenced before assignment

by rearranging the code so the variable is set.

Fixes issue #5200.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>