util: Wait until service is removed before setting the parent
If parent is set to None too early, we may break any operations that
happen during stopService() as the master attribute will no longer be
available. For example, this error may be observed:

  File "<...>/master/buildbot/process/buildrequestdistributor.py",
line 513, in _maybeStartBuildsOnBuilder

    claimed_at_epoch = self.master.reactor.seconds()

builtins.AttributeError: 'NoneType' object has no attribute 'reactor'