Fix a test failure when influxdb is installed
A test failed as influxdb insists the port should be an integer since
version 3.0 [1].

    [ERROR]
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
        result = current_context.run(gen.send, result)
      File "/home/yen/buildbot/master/buildbot/test/unit/test_stats_service.py", line 131, in test_influxdb_not_installed
        InfluxStorageService("fake_url", "fake_port", "fake_user", "fake_password",
      File "/home/yen/buildbot/buildbot/master/buildbot/statistics/storage_backends/influxdb_client.py", line 46, in __init__
        self.client = InfluxDBClient(self.url, self.port, self.user,
      File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 108, in __init__
        self.__port = int(port)
    builtins.ValueError: invalid literal for int() with base 10: 'fake_port'

    buildbot.test.unit.test_stats_service.TestInfluxDB.test_influxdb_not_installed

[1] https://github.com/influxdata/influxdb-python/commit/0a193cf2e87327eec8110815efa14f1f70765628